# Generated by Django 3.2.25 on 2024-09-09 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
