version: '3.4'

services:
  web:
    image: ipodapp
    build:
      context: src/ipod
    command: ["sh", "-c", "./wait-for-it.sh db:3306 -- configure-cups.sh && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 configure-cups.sh && uv run -- flask run -p 8000 --host 0.0.0.0"]
    environment:
      - FLASK_DEBUG=1
    ports:
      - 8000:8000
      - 5678:5678
      - 631:631