[project]
name = "ipod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django==4.2.16",
    "mysqlclient==2.2.4",
    "pycups==2.0.4",
    "python-dotenv>=1.0.1",
]
