version: '3.4'

services:
  print:
    image: print
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "PRINTER_NAME=PDF"
      - "HOST=13.65.122.43:631"
      - "FOLDER_PATH=/upload"
    volumes:
      - /home/vscode/upload/:/upload/

