version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "ipod"
      MYSQL_USER: "ipoduser"
      MYSQL_PASSWORD: "ipodpassword"
      MYSQL_ROOT_PASSWORD: "ipodadminpassword"
    platform: linux/amd64
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  job:
    build:
      context: .
    command: sh -c "./wait-for-it.sh db:3306 -- python app.py"
    volumes:
      - ./wait-for-it.sh:/app/wait-for-it.sh
      - /home/vscode/.ssh/:/home/vscode/.ssh/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: "ipod"
      MYSQL_USER: "ipoduser"
      MYSQL_PASSWORD: "ipodpassword"
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      SFTP_SSH_KEY_PATH: /home/vscode/.ssh/id_ed25519
      SFTP_SERVER: 13.66.66.116
      SFTP_PORT: 4422
      SFTP_USERNAME: vscode
      SFTP_REMOTE_PATH: /home/vscode/upload/
      SFTP_LOCAL_PATH: /home/vscode/upload/
    platform: linux/amd64

volumes:
  db_data: